joe = User.create(name: "Joe Gelay")
justin = User.create(name: "Justin Sabath")
jesse = User.create(name: "Jesse Pope")
damon = User.create(name: "Damon Chivers")

morning = Journal.create(name: "Morning")
afternoon = Journal.create(name: "Afternoon")
night = Journal.create(name: "Night")

e1 = Entry.create(content: "Morning test one", user: joe, journal: morning)
e2 = Entry.create(content: "Morning test two", user: joe, journal: morning)
e3 = Entry.create(content: "Morning test three", user: justin, journal: morning)
e4 = Entry.create(content: "Morning test four", user: joe, journal: morning)
e5 = Entry.create(content: "Afternoon test one", user: jesse, journal: afternoon)
e6 = Entry.create(content: "Afternoon test two", user: damon, journal: afternoon)
e7 = Entry.create(content: "Afternoon test three", user: damon, journal: afternoon)
e8 = Entry.create(content: "Afternoon test four", user: justin, journal: afternoon)
e9 = Entry.create(content: "Night test one", user: joe, journal: night)
e10 = Entry.create(content: "Night test two", user: justin, journal: night)
e11 = Entry.create(content: "Night test three", user: damon, journal: night)
e12 = Entry.create(content: "Night test four", user: justin, journal: night)